# Generated by Django 3.2.23 on 2024-01-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='../standard_profile_impkoj', upload_to='images/'),
        ),
    ]
